# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-09 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('summit_auth', '0004_auto_20190502_0752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_id', models.CharField(max_length=255, unique=True, verbose_name='Page ID')),
                ('title', models.CharField(default='No Title', max_length=64)),
                ('html_body', models.TextField(default='', verbose_name='Document Body')),
                ('is_published', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_doc_created', to='summit_auth.UserProfile', verbose_name='Created By')),
                ('last_edited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_last_edit_by', to='summit_auth.UserProfile', verbose_name='Last Edited By')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
