# Generated by Django 3.2.4 on 2021-08-15 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summit_auth', '0005_auto_20210815_1631'),
        ('summit_docs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='document_doc_created', to='summit_auth.userprofile', verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='document',
            name='last_edited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='document_last_edit_by', to='summit_auth.userprofile', verbose_name='Last Edited By'),
        ),
    ]
