# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-15 03:39
from __future__ import unicode_literals

from django.db import migrations

from summit.libs.auth.models import CESUnit


def add_cpcesu(arg1, arg2):
    CESUnit.objects.get_or_create(name="Colorado Plateau")


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('summit_auth', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_cpcesu),
    ]
