# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-02 05:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summit_auth', '0002_create_cpcesu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='group',
        ),
    ]
