# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-07 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summit_auth', '0002_auto_20190206_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='summit_auth.UserGroup'),
        ),
    ]
