# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-11 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit_auth', '0003_auto_20181210_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='With this checked, it allows this user to access the administrative backend', verbose_name='Admin site access?'),
        ),
    ]
