# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-02 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summit_auth', '0003_remove_user_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='assigned_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='summit_auth.UserGroup', verbose_name='Assigned Organization'),
        ),
    ]
