# Generated by Django 3.2.8 on 2021-11-02 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summit_auth', '0006_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='CESU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('logo', models.ImageField(blank=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.EmailField(default='default@email.test', max_length=255, unique=True, verbose_name='Contact Email Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='organization',
            name='type',
            field=models.CharField(blank=True, choices=[('PARTNER', 'Partner'), ('FEDERAL AGENCY', 'Federal Agency')], max_length=50, verbose_name='Organization Type'),
        ),
        migrations.AddField(
            model_name='organization',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='headshot',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
