# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-12 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summit_auth', '0006_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile'},
        ),
    ]
