# Generated by Django 3.2.8 on 2021-11-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit_auth', '0007_auto_20211101_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='Contact Email Address'),
        ),
    ]
