# Generated by Django 3.2.8 on 2021-11-16 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit_auth', '0009_cesu_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cesu',
            name='contact',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
