# Generated by Django 3.2.8 on 2021-11-16 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summit_auth', '0010_cesu_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cesu',
            name='email',
        ),
    ]
