# Generated by Django 3.2.8 on 2021-11-16 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit_auth', '0011_remove_cesu_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='type',
            field=models.CharField(blank=True, choices=[('Partner', 'Partner'), ('Federal Agency', 'Federal Agency')], max_length=50, verbose_name='Organization Type'),
        ),
    ]
