# Generated by Django 3.2.8 on 2022-02-13 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summit_auth', '0013_auto_20211122_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cesu',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_cesu', to='summit_auth.cesu', verbose_name='CESU'),
        ),
    ]
