# Generated by Django 3.2.8 on 2022-02-27 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit_auth', '0015_alter_userprofile_assigned_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_cesus',
            field=models.ManyToManyField(to='summit_auth.CESU'),
        ),
    ]
