# Generated by Django 3.2.8 on 2022-02-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit_auth', '0016_user_user_cesus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_cesus',
            field=models.ManyToManyField(blank=True, related_name='user_cesus', to='summit_auth.CESU'),
        ),
    ]
