# Generated by Django 3.2.8 on 2022-03-06 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit_auth', '0017_alter_user_user_cesus'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('VIEWER', 'Viewer'), ('USER', 'User'), ('ADMIN', 'Admin'), ('SUPERUSER', 'Superuser')], default=('VIEWER', 'Viewer'), max_length=50, null=True),
        ),
    ]
