# Generated by Django 3.2.8 on 2022-04-18 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit_auth', '0018_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('VIEWER', 'Viewer'), ('USER', 'User'), ('ADMIN', 'Admin')], default=('VIEWER', 'Viewer'), max_length=50, null=True),
        ),
    ]
