# Generated by Django 3.2.8 on 2022-05-23 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summit_auth', '0020_organization_abbrv'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPCESURole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(blank=True, choices=[('VIEWER', 'Viewer'), ('USER', 'User'), ('ADMIN', 'Admin')], default=('VIEWER', 'Viewer'), max_length=50, null=True)),
                ('cesu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_cesu', to='summit_auth.cesu')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cesu_role_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
