# Generated by Django 3.2.8 on 2022-05-23 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summit_auth', '0021_cpcesurole'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CPCESURole',
            new_name='CESURole',
        ),
    ]
