# Generated by Django 3.2.8 on 2022-08-23 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit_auth', '0023_auto_20220705_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cesurole',
            name='role',
            field=models.CharField(blank=True, choices=[('VIEWER', 'Viewer'), ('USER', 'User'), ('ADMIN', 'Admin'), ('SUSPENDED', 'Suspended')], default=('VIEWER', 'Viewer'), max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('VIEWER', 'Viewer'), ('USER', 'User'), ('ADMIN', 'Admin'), ('SUSPENDED', 'Suspended')], default=('VIEWER', 'Viewer'), max_length=50, null=True),
        ),
    ]
