# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-12 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(help_text='The title of the project', max_length=500, unique=True)),
                ('short_summary', models.CharField(help_text='This field is displayed in "overviews" such as the projects listing page.', max_length=500)),
                ('description', models.TextField(help_text='A free-form description of the plugin.')),
                ('sensitive', models.BooleanField(default=False, help_text='True if data is sensitive and cannot be revealed to the public.')),
                ('budget', models.DecimalField(decimal_places=2, help_text='Any amount that pertains to the overall budget of a project.', max_digits=12)),
                ('student_support', models.CharField(choices=[('GRAD', 'Graduate'), ('UGRAD', 'Undergraduate'), ('BOTH', 'Graduate and Undergraduate'), ('NONE', 'None')], default='NONE', max_length=2)),
            ],
        ),
    ]
