# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-07 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summit_auth', '0003_auto_20190206_2354'),
        ('summit_projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='federal_agency',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='federal_agency', to='summit_auth.FederalAgency'),
        ),
    ]
