# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-12 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit_projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='student_support',
            field=models.CharField(choices=[('GRAD', 'Graduate'), ('UGRAD', 'Undergraduate'), ('BOTH', 'Graduate and Undergraduate'), ('NONE', 'None')], default='NONE', max_length=5),
        ),
    ]
