# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-02 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit_projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='youth_vets',
            field=models.CharField(blank=True, choices=[('NO', 'NO'), ('YES', 'YES')], max_length=500, null=True),
        ),
    ]
