# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-17 00:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summit_auth', '0003_auto_20190206_2354'),
        ('summit_projects', '0002_project_federal_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cesu_unit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cesu_unit', to='summit_auth.CESUnit'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Drafting'), ('EXEC', 'Executed'), ('CLOSE', 'Closed')], default='DRAFT', max_length=5),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.DecimalField(decimal_places=2, help_text='Any amount that pertains to the overall budget of a project.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='project',
            name='federal_agency',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='federal_agency', to='summit_auth.FederalAgency'),
        ),
        migrations.AlterField(
            model_name='project',
            name='partner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='partner', to='summit_auth.Partner'),
        ),
        migrations.AlterField(
            model_name='project',
            name='student_support',
            field=models.CharField(choices=[('GRAD', 'Graduate'), ('UGRAD', 'Undergraduate'), ('BOTH', 'Graduate and Undergraduate'), ('NONE', 'None')], default='NONE', max_length=4),
        ),
    ]
