# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-09 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit_projects', '0002_auto_20190509_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='fiscal_year',
            field=models.PositiveSmallIntegerField(blank=True, default=2019, null=True, verbose_name='Fiscal Year'),
        ),
    ]
