# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-12 22:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit_projects', '0002_auto_20181212_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.DecimalField(decimal_places=3, help_text='Any amount that pertains to the overall budget of a project.', max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
    ]
