# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-02 20:34
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit_projects', '0002_auto_20190502_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, default=1000, help_text='Initial funding amount (USD)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('9999999.99'))], verbose_name='Initial'),
        ),
    ]
