# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-09 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summit_projects', '0003_auto_20190509_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='discipline',
            field=models.CharField(blank=True, choices=[('NONE', 'None'), ('NATURAL', 'Natural'), ('CULTURAL', 'Cultural'), ('SOCIAL', 'Social'), ('INTERDISCIPLINARY', 'Interdisciplinary')], default='NONE', help_text='The discipline related to the project', max_length=21),
        ),
        migrations.AlterField(
            model_name='project',
            name='federal_agency',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='federal_agency', to='summit_auth.FederalAgency', verbose_name='Agency'),
        ),
        migrations.AlterField(
            model_name='project',
            name='field_of_science',
            field=models.CharField(blank=True, choices=[('NONE', 'None'), ('ENVIRO_SCI', 'Environmental Sciences'), ('LIFE_SCI', 'Life Sciences'), ('MATH_CS', 'Math & Computer Sciences'), ('PHYSICAL_SC', 'Physical Sciences'), ('SOCIAL_SC', 'Social Sciences')], default='NONE', help_text='A specific field of science for the project.', max_length=500, verbose_name='Field of Science'),
        ),
        migrations.AlterField(
            model_name='project',
            name='field_of_science_sub',
            field=models.CharField(blank=True, choices=[('ES_AS', 'ES - Atmospheric Sciences'), ('ES_GS', 'ES - Geological Sciences'), ('ES_O', 'ES – Oceanography'), ('ES_ES', 'ES - Environmental Sciences NEC'), ('LS_BI', 'LS - Biological (excl.Environmental)'), ('ES_EB', 'LS - Environmental Biology'), ('LS_AS', 'LS - Agricultural Science'), ('LS_MS', 'LS - Medical Science'), ('LS_LS', 'LS - Life Science NEC')], default='ES_AS', max_length=100, null=True, verbose_name='Sub-Fields (Field of Science)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='partner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner', to='summit_auth.Partner'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pp_i',
            field=models.ForeignKey(blank=True, default=None, help_text='Partner Principle Investigator', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pp_i', to='summit_auth.UserProfile', verbose_name='Partner Principle Investigator'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_manager', to='summit_auth.UserProfile', verbose_name='Agency Project Manager'),
        ),
        migrations.AlterField(
            model_name='project',
            name='src_of_funding',
            field=models.CharField(blank=True, choices=[('NONE', 'None'), ('PARK', 'Park Base'), ('REGION', 'Region Base'), ('SOURCE', 'NR Project Fund Source'), ('PROGRAM', 'I&M Program'), ('OTHER_PROJECT_SOURCE', 'Other Service-wide Project Source'), ('REA_FEE_80', '80% REA Fee'), ('REA_FEE_20', '20% REA Fee'), ('OTHER_NPS_SOURCE', 'Other NPS Appropriated Source'), ('OTHER', 'OTHER-non-NPS')], default='NONE', help_text='The source of the funding', max_length=500, verbose_name='Source of Funding'),
        ),
    ]
