# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-31 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summit_auth', '0007_auto_20181212_1323'),
        ('summit_projects', '0003_auto_20181212_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='partner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='partner', to='summit_auth.Partner'),
        ),
    ]
