# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-07 19:29
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summit_projects', '0004_auto_20190502_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='abbrv',
            field=models.TextField(default='GRCA', max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Initial funding amount (USD)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('9999999.99'))], verbose_name='Initial'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cesu_unit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cesu_unit', to='summit_auth.CESUnit', verbose_name='CESUnit'),
        ),
        migrations.AlterField(
            model_name='project',
            name='staff_member',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_member', to='summit_auth.UserProfile', verbose_name='Staff Member'),
        ),
    ]
