# Generated by Django 3.2.4 on 2021-08-15 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit_projects', '0004_auto_20190509_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='final_report',
            field=models.BooleanField(blank=True, default=False, verbose_name='Final Report'),
        ),
        migrations.AlterField(
            model_name='project',
            name='fiscal_year',
            field=models.PositiveSmallIntegerField(blank=True, default=2021, null=True, verbose_name='Fiscal Year'),
        ),
        migrations.AlterField(
            model_name='project',
            name='perm_share',
            field=models.BooleanField(blank=True, default=False, verbose_name='Permission to share'),
        ),
        migrations.AlterField(
            model_name='project',
            name='req_iacuc',
            field=models.BooleanField(blank=True, default=False, verbose_name='Requires IACUC Review/ Concurrence'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sci_method',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='sensitive',
            field=models.BooleanField(blank=True, default=False, help_text='True if data is sensitive and cannot be revealed to the public.', verbose_name='Sensitive'),
        ),
    ]
