# Generated by Django 3.2.4 on 2021-08-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit_projects', '0005_auto_20210815_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='modification',
            name='mod_status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Drafting'), ('APPROVED', 'Approved'), ('EXECUTED', 'Executed'), ('CLOSED', 'Closed'), ('LEGACY', 'Legacy')], default=('DRAFT', 'Drafting'), max_length=50),
        ),
    ]
