# Generated by Django 3.2.4 on 2021-09-03 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit_projects', '0007_project_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='deleted',
        ),
        migrations.AlterField(
            model_name='modification',
            name='mod_status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Drafting'), ('APPROVED', 'Approved'), ('EXECUTED', 'Executed'), ('CLOSED', 'Closed'), ('LEGACY', 'Legacy'), ('DELETED', 'Deleted')], default=('DRAFT', 'Drafting'), max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Drafting'), ('APPROVED', 'Approved'), ('EXECUTED', 'Executed'), ('CLOSED', 'Closed'), ('LEGACY', 'Legacy'), ('DELETED', 'Deleted')], default=('DRAFT', 'Drafting'), max_length=50),
        ),
    ]
