# Generated by Django 3.2.4 on 2021-09-21 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit_projects', '0008_auto_20210902_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='last_status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Drafting'), ('APPROVED', 'Approved'), ('EXECUTED', 'Executed'), ('CLOSED', 'Closed'), ('LEGACY', 'Legacy'), ('ARCHIVED', 'Archived')], default=('DRAFT', 'Drafting'), max_length=50),
        ),
        migrations.AlterField(
            model_name='modification',
            name='mod_status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Drafting'), ('APPROVED', 'Approved'), ('EXECUTED', 'Executed'), ('CLOSED', 'Closed'), ('LEGACY', 'Legacy'), ('ARCHIVED', 'Archived')], default=('DRAFT', 'Drafting'), max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Drafting'), ('APPROVED', 'Approved'), ('EXECUTED', 'Executed'), ('CLOSED', 'Closed'), ('LEGACY', 'Legacy'), ('ARCHIVED', 'Archived')], default=('DRAFT', 'Drafting'), max_length=50),
        ),
    ]
