# Generated by Django 3.2.8 on 2021-10-19 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summit_projects', '0009_auto_20210920_2056'),
        ('summit_projects', '0009_auto_20211011_2130'),
    ]

    operations = [
    ]
