# Generated by Django 3.2.8 on 2022-02-15 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summit_projects', '0011_auto_20211115_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='last_status',
        ),
    ]
