# Generated by Django 3.2.8 on 2022-02-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit_projects', '0012_remove_project_last_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='local_num',
            field=models.CharField(blank=True, help_text='Local number.', max_length=500, null=True, verbose_name='Local #'),
        ),
    ]
