# Generated by Django 3.2.8 on 2022-02-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit_projects', '0013_project_local_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Drafting'), ('APPROVED', 'Approved'), ('EXECUTED', 'Executed'), ('CLOSED', 'Closed'), ('LEGACY', 'Legacy'), ('ARCHIVED', 'Archived')], default=('DRAFT', 'Drafting'), max_length=50, null=True),
        ),
    ]
