# Generated by Django 3.2.8 on 2022-04-18 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit_projects', '0015_auto_20220220_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummitID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('type', models.CharField(max_length=500)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='summit_index',
            field=models.IntegerField(default=1),
        ),
    ]
