# Generated by Django 3.2.8 on 2022-04-18 04:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('summit_projects', '0016_auto_20220417_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='summit_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
