# Generated by Django 3.2.8 on 2022-04-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summit_projects', '0017_file_summit_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='location',
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='location', to='summit_projects.Location', verbose_name='Place'),
        ),
    ]
