# Generated by Django 3.2.8 on 2022-06-14 22:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('summit_projects', '0019_alter_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='modfile',
            name='summit_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='modfile',
            name='summit_index',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='location', to='summit_projects.Location', verbose_name='Location'),
        ),
    ]
