# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-26 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('summit_notifications', '0001_initial'),
        ('summit_projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summit_projects.Project'),
        ),
    ]
